project/urls.py
from django.urls import path
from .views import ListeProjetsView, DetailProjetView
app_name = 'project'

urlpatterns = [
    path('', ListeProjetsView.as_view(), name='projects'),
    path('<int:pk>/', DetailProjetView.as_view(), name='project_detail'),
]

project/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Projet(models.Model):
    titre = models.CharField(max_length=100)
    link = models.URLField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    thumbnail = models.ImageField(upload_to='projects/thumbnails/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='in progress')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.titre

work/models.py
from django.db import models

# Create your models here.

project/views.py
from django.views.generic import ListView, DetailView
from .models import Projet, Category


class ListeProjetsView(ListView):
    model = Projet
    template_name = 'project/project_list.html'
    context_object_name = 'projects'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class DetailProjetView(DetailView):
    model = Projet
    template_name = 'project/project_detail.html'
    context_object_name = 'project'


work/views.py
from django.shortcuts import render

# Create your views here.

templates/about/about.html
{% extends 'base.html' %}

{% block title %}About- My Portfolio{% endblock %}

{% block content %}
<div class="container">
    <header class="header">
        <h1 class="name">BASSANE <span>B. O. Joseph</span></h1>
        <p class="title">Dévéloppeur-Designer</p>
        <div class="contact-info">
            <p><a href="nanocreator07@gmail.Com">nanocreator07@gmail.Com</a></p>
            <p>+228 92 60 28 49</p>
            <p>Lomé, TOGO</p>
        </div>
    </header>

    <section class="profile">
        <h2>Profile</h2>
        <p>Graphic Designer, UX-UI Designer, FullStack Dev...</p>
    </section>

    <section class="experience">
        <h2>Experience</h2>
        <div class="job">
            <h3>Company Name</h3>
            <p>Job Title | 2034 - Present</p>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium...</p>
        </div>
        <div class="job">
            <h3>Company Name</h3>
            <p>Job Title | 2032 - 2034</p>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium...</p>
        </div>
        <div class="job">
            <h3>Company Name</h3>
            <p>Job Title | 2030 - 2032</p>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium...</p>
        </div>
    </section>

    <section class="skills">
        <h2>Skills</h2>
        <ul>
            <li>Graphic Design</li>
            <li>UI/UX Design</li>
            <li>Web Design</li>
            <li>Content Development</li>
            <li>Copywriting</li>
            <li>Corporate Blogging</li>
            <li>Project Management</li>
            <li>Market Research</li>
        </ul>
    </section>

    <section class="education">
        <h2>Education</h2>
        <div class="degree">
            <h3>Degree Title</h3>
            <p>University | 2030-34</p>
            <p>Major Subject</p>
        </div>
        <div class="degree">
            <h3>Degree Title</h3>
            <p>University | 2028-30</p>
            <p>Major Subject</p>
        </div>
        <div class="degree">
            <h3>Degree Title</h3>
            <p>University | 2026-28</p>
            <p>Major Subject</p>
        </div>
    </section>
</div>
{% endblock %}

templates/blog/article_detail.html
{% extends 'base.html' %}

{% block title %}Blog - My Portfolio{% endblock %}

{% block content %}
    <h1>Detail²</h1>
        {% for article in article %}

                <div class="card">
                    <h3>{{ article.name }}</h3>
                    <p>{{ article.description }}</p>
                </div>
            {% endif %}
        {% endfor %}
{% endblock %}

templates/blog/article_list.html
{% extends 'base.html' %}

{% block title %}Blog - My Portfolio{% endblock %}

{% block content %}
<div class="project-list">
    <div class="project">
        <h1>Blog</h1>
        <p>Restez informé, des connexions </p>
        <div class="project-click">Tech - Design - Code</div>
    </div>


{% for category in categories %}
    <h2 class="categorie_project">{{ category.title }}</h2>
    <div class="card-grid">
        {% for article in articles %}
            {% if article.category == category %}
                <div class="card">
                    <h3><a href="{% url 'blog:article_detail' article.pk %}">{{ article.name }}</a></h3>
                    <p>{{ article.description }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

</div>

{% endblock %}

templates/core/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact - Mon Portfolio{% endblock %}

{% block content %}
<section class="contact-section">

        <h2 class="section-title">Contactez-moi</h2>
        <p class="section-description">N'hésitez pas à me contacter pour toute question ou proposition.</p>

        <form method="post" class="contact-form">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Nom</label>
                {{ form.name }}
                {% if form.name.errors %}
                    <div class="error-message">{{ form.name.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">Email</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="error-message">{{ form.email.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.subject.id_for_label }}">Sujet</label>
                {{ form.subject }}
                {% if form.subject.errors %}
                    <div class="error-message">{{ form.subject.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.message.id_for_label }}">Message</label>
                {{ form.message }}
                {% if form.message.errors %}
                    <div class="error-message">{{ form.message.errors }}</div>
                {% endif %}
            </div>

            <button type="submit" class="submit-btn">Envoyer</button>
        </form>

</section>
{% endblock %}

templates/core/newsletters.html
{% extends 'base.html' %}

{% block content %}
<h2>S'inscrire à la newsletter</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">S'inscrire</button>
</form>
{% endblock %}

templates/project/poject_detail.html
{% extends 'base.html' %}

{% block title %}Projects - Mon Portfolio{% endblock %}

{% block content %}
<div class="project-list">
    <div class="project">
        <h1>Projets</h1>
        <p>Pas Juste des Projets mais des créations, de la créativité et du professionnalisme </p>
        <div class="project-click">Vous avez un Projet ? écrivez moi</div>
    </div>



    <div class="card-grid">
        {% for project in project %}

                <div class="card">
                    <h3>{{ project.titre }}</h3>
                    <p>{{ project.description }}</p>
                </div>
        {% endfor %}
    </div>


</div>

{% endblock %}

templates/project/project_list.html
{% extends 'base.html' %}

{% block title %}Projects - Mon Portfolio{% endblock %}

{% block content %}
<div class="project-list">
    <div class="project">
        <h1>Projets</h1>
        <p>Pas Juste des Projets mais des créations, de la créativité et du professionnalisme </p>
        <div class="project-click">Vous avez un Projet ? écrivez moi</div>
    </div>


{% for category in categories %}
    <h2 class="categorie_project">{{ category.name }}</h2>
    <div class="card-grid">
        {% for project in projects %}
            {% if project.category == category %}
                <div class="card">
                    <h3><a href="{% url 'project:project_detail' project.pk %}">{{ project.titre }}</a></h3>

                    <p>{{ project.description }}</p>
                    <h5>{{ project.date_created }}</h5>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

</div>

{% endblock %}

templates/work/work_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>